In [2]:
import sys
# 导入上级目录，不然无法使父文件夹的代码
sys.path.append('../..')

In [8]:
from pyltp import SentenceSplitter

In [3]:
import pandas as pd

In [4]:
news_corpus_path = '../../word2vec/news_text/news_00'

In [5]:
f_news = open(news_corpus_path)

In [376]:
news_line = next(f_news)

sentencence = [s.replace('\\\\n','') for s in SentenceSplitter.split(news_line) if len(s.replace('\\\\n',''))>3]

sentencence

['"2017年4月27日，在首尔光化门广场，民众在集会上手举反“萨德”标语。',
 '（新华社记者姚琪琳摄）新华社北京6月7日电（记者张旌）韩国国防部官员6日说，针对“萨德”在韩部署事宜，国防部方面已准备重新进行一场大规模的环境评估。',
 '完成新评估可能需要一年时间，“萨德”部署工作也将因此推迟或暂停。',
 '此前一天，青瓦台方面指责国防部试图把“萨德”对周围环境影响的评估过程“大事化小”，要求彻查此事。',
 '【环评“猫腻”遭曝光】韩国国防部官员6日向韩联社记者透露，青瓦台要求彻查“萨德”环境评估过程后，国防部已着手开展准备工作，将进行一场大规模的全面评估，预计可能耗时一年左右。',
 '根据这名官员的说法，国防部将就此事与青瓦台方面沟通后再制定详细方案，具体计划尚未确定。',
 '这名官员同时透露，目前，针对“萨德”用地的小规模环境评估正在进行中，预计将于本月底结束。',
 '此前一天，青瓦台方面表示，经调查发现，国防部在“萨德”环境评估过程中存在“猫腻”，试图“大事化小”，绕过相关法律规定。',
 '根据韩国相关法律，要在面积超过33万平方米的土地建新设施时，必须首先通过全面环境评估，以确定对周围环境影响的程度。',
 '韩国为美军提供的“萨德”部署地总面积约为70万平方米，按规定本应接受大规模环境评估。',
 '不过，根据青瓦台方面的说法，国防部把这块地分两批提供给美军，第一批面积为32万平方米，刚好避开全面环境评估的规定，只需接受小规模非正式评估。',
 '余下的部分稍晚些提供，也设法躲过了大规模环境评估。',
 '【部署进程或推迟】青瓦台方面发起这次调查，主要原因是要查明“另有4台发射架秘密运抵韩国”一事，而环境评估的“猫腻”正是在这一调查过程中被曝光。',
 '上月30日，青瓦台方面表示，总统文在寅获悉除目前已在韩部署的两台“萨德”系统移动发射架外，另有4台发射架已经秘密运抵韩国，感到“非常震惊”，要求彻查。',
 '青瓦台公报首席秘书尹永灿5日在记者会上说，调查已确认，瞒报事件主要责任人是国防部政策室长魏昇镐。',
 '由于魏昇镐已被停职，国防部还需重新确定一名指挥环境评估工作的负责人。',
 '青瓦台方面同时表示，将就此事展开进一步调查，以查明国防部长官韩民求和前总统朴槿惠时期的国家安保室长金宽镇是否与瞒报事件有关联。',
 '针对环评“

In [22]:
import jieba

In [30]:
sen_cuted = [jieba.cut(sen)) for sen in sentencence]

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 2.739 seconds.
Prefix dict has been built succesfully.


In [268]:
sen_cuted

['" 2017 年 5 月 29 日 ， 在 法国巴黎 郊外 的 凡尔赛宫 ， 法国 总统 马克 龙 出席 新闻 发布会 。',
 '（ 新华 / 法新 ） 新华社 北京 6 月 7 日电 （ 记者 张 旌 ） 法国 定于 6 月 11 日 举行 议会选举 首轮 投票 。',
 '最新 民调 结果显示 ， 总统 埃马 纽埃 尔 · 马克 龙 领导 的 “ 共和国 前进 ” 运动 将 在 这场 选举 中 获得 “ 压倒性 胜利 ” ， 不仅 将 赢得 议会 多数 席位 ， 数量 还 可望 创下 1968 年 以来 历届 执政党 的 最高值 。',
 '对 马克 龙 而言 ， 要 坐 稳 总统 宝座 ， 赢得 这场 选举 至关重要 。',
 '法国议会 选举 有着 “ 第三轮 选举 ” 之称 ， 将 决定 议会 多数派 归属 ， 影响 法国政府 未来 五年 的 实际 执政 方向 。',
 '民调 机构 益普索 集团 6 日 公布 的 最新 民调 结果显示 ， 在 本月 11 日 举行 的 议会选举 首轮 投票 中 ， 马克 龙 领导 的 “ 共和国 前进 ” 运动 得票率 将 可达 29.5% 。',
 '相比之下 ， 共和党 阵营 得票率 预计 为 23% ， 极右翼 “ 国民 阵线 ” 得票率 预计 为 17% ， 极 左翼 政治势力 “ 不屈 法国 ” 得票率 预计 为 12.5% ， 而 社会党 有望 获得 8.5% 的 选票 。',
 '这项 民调 同时 显示 ， 在 定于 6 月 18 日 举行 的 议会选举 第二轮 投票 中 ， “ 共和国 前进 ” 运动 将 获得 议会下院 577 个 议席 中 的 385 至 415 个 议席 。',
 '在 一周 前 进行 的 另 一场 类似 民调 中 ， “ 共和国 前进 ” 运动 预计 得票率 曾 高达 31% 。',
 '新政府 两名 部长 被 曝 牵涉 “ 空饷 门 ” 后 ， “ 共和国 前进 ” 运动 的 支持率 似乎 有 下跌 之势 。',
 '不过 ， 民调 结果显示 ， “ 空饷 门 ” 事件 并未 影响 马克 龙 在 民众 心目 中 的 形象 。',
 '约 60% 的 受访者 表示 ， 他们 对 马克 龙 的 表现 感到 满意 。',
 '“ 共和国 前进 ” 运动 去年 6 月 成立 ， 眼

In [37]:
>>> from sklearn.feature_extraction.text import CountVectorizer
>>> corpus = [
...     'This is the first document.',
...     'This document is the second document.',
...     'And this is the third one.',
...     'Is this the first document?',
... ]
>>> vectorizer = CountVectorizer()
>>> X = vectorizer.fit_transform(sen_cuted)
>>> print(vectorizer.get_feature_names())
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
>>> print(X.toarray())  


['11', '12', '17', '18', '1968', '2017', '23', '29', '31', '385', '415', '577', '60', '一周', '一场', '下跌', '不仅', '不屈', '不能', '不过', '两名', '举行', '之势', '之称', '事件', '五年', '他们', '以来', '似乎', '公布', '共和党', '共和国', '决定', '凡尔赛宫', '出席', '创下', '前进', '北京', '历届', '压倒性', '去年', '发布会', '受访者', '可望', '可达', '同时', '名义', '国民', '埃马', '多数', '多数派', '如果', '定于', '宝座', '实际', '届时', '左翼', '席位', '并未', '归属', '形象', '影响', '得票率', '心目', '总统', '感到', '成立', '执政', '执政党', '投票', '担忧', '支持率', '政治势力', '数量', '新华', '新华社', '新政府', '新闻', '方向', '日电', '显示', '最新', '最高值', '有人', '有望', '有着', '未来', '本月', '机构', '极右翼', '此前', '民众', '民调', '沦为', '法国', '法国巴黎', '法国政府', '法国议会', '法新', '满意', '牵涉', '甚至', '益普索', '相比之下', '眼下', '社会党', '空饷', '第三轮', '第二轮', '类似', '纽埃', '组建', '结果显示', '而言', '联合政府', '胜利', '至关重要', '获得', '表现', '表示', '被迫', '议会', '议会下院', '议会选举', '议席', '记者', '赢得', '运动', '这场', '这项', '进行', '选举', '选票', '郊外', '部长', '阵线', '阵营', '集团', '预计', '领导', '首轮', '马克', '高达']
[[0 0 0 ... 0 1 0]
 [1 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 

In [43]:
X[0].toarray()

array([[0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [48]:
X.shape

(14, 143)

In [50]:
fns = vectorizer.get_feature_names()

In [51]:
import numpy as np

In [59]:
np.where(X[0].toarray()[0])

(array([  5,   7,  33,  34,  41,  64,  77,  94,  95, 133, 141]),)

In [60]:
[fns[i] for i in np.where(X[0].toarray()[0])[0]]

['2017', '29', '凡尔赛宫', '出席', '发布会', '总统', '新闻', '法国', '法国巴黎', '郊外', '马克']

In [45]:
[len(i.split()) for i in sen_cuted]

[22, 27, 48, 16, 24, 37, 39, 37, 22, 24, 21, 15, 17, 36]

In [47]:
vectorizer.

# CountVectorizer

In [101]:
vectorizer = CountVectorizer()

In [259]:
>>> corpus = [
...     'This is the first document.',
...     'This is the second second document.',
...     'And the third one.',
...     'Is  a is this the first document? ',
... ]
>>> X = vectorizer.fit_transform(corpus)
>>> X                              


<4x13 sparse matrix of type '<class 'numpy.float64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [103]:
vectorizer.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [104]:
analyze = vectorizer.build_analyzer()

In [105]:
analyze("This is a text document to analyze. ")

['this', 'is', 'text', 'document', 'to', 'analyze']

In [231]:
xa = X.toarray()

In [232]:
vectorizer.vocabulary_

{'and': 0,
 'document': 1,
 'first': 2,
 'is': 3,
 'one': 4,
 'second': 5,
 'the': 6,
 'third': 7,
 'this': 8}

In [233]:
xa

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 2, 0, 0, 1, 0, 1]], dtype=int64)

### For the first line

In [195]:
>>> xa = np.array([[3, 0, 1],
...           [2, 0, 0],
...           [3, 0, 0],
...           [4, 0, 0],
...           [3, 2, 0],
...           [3, 0, 2]])


In [234]:
tf = xa[0]

In [235]:
n = xa.shape[0]

In [236]:
n

4

In [237]:
df = np.sum(xa!=0,axis=0)

In [238]:
df

array([1, 3, 2, 3, 1, 1, 4, 1, 3])

In [239]:
idf = np.log((n+1)/(df+1))+1

In [240]:
idf

array([1.91629073, 1.22314355, 1.51082562, 1.22314355, 1.91629073,
       1.91629073, 1.        , 1.91629073, 1.22314355])

In [241]:
tf_idf = tf*idf
tf_idf

array([0.        , 1.22314355, 1.51082562, 1.22314355, 0.        ,
       0.        , 1.        , 0.        , 1.22314355])

In [242]:
norm_sum = np.sqrt(np.sum(np.square(tf_idf)))

In [243]:
tf_idf/norm_sum

array([0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
       0.        , 0.35872874, 0.        , 0.43877674])

In [244]:
>>> from sklearn.feature_extraction.text import TfidfTransformer
>>> transformer = TfidfTransformer()
>>> transformer   


TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)

In [245]:
tfidf_com = transformer.fit_transform(xa)

In [246]:
tfidf_com.toarray()

array([[0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674],
       [0.        , 0.27230147, 0.        , 0.27230147, 0.        ,
        0.85322574, 0.22262429, 0.        , 0.27230147],
       [0.55280532, 0.        , 0.        , 0.        , 0.55280532,
        0.        , 0.28847675, 0.55280532, 0.        ],
       [0.        , 0.34934021, 0.43150466, 0.69868042, 0.        ,
        0.        , 0.28560851, 0.        , 0.34934021]])

In [247]:
>>> from sklearn.feature_extraction.text import TfidfVectorizer


In [380]:
S = 9

In [383]:
S= 888 if S > 10 else None

In [385]:
set(i for i in range(9))

{0, 1, 2, 3, 4, 5, 6, 7, 8}

In [263]:
def func_tes(x):
    print(x)
    return x.split()

In [281]:
! rm -rf ../../word2vec/stopwords/.ipynb_checkpoints

In [334]:
STOPWORD = []

In [335]:
import os
pre = '../../word2vec/stopwords/'
for i in os.listdir(pre):
    with open(pre+i) as f:
        STOPWORD += [i for i in f.readlines()]

In [336]:
STOPWORD =set(STOPWORD)

In [337]:
STOPWORD = list(STOPWORD)

In [339]:
with open('stopwords.txt','w') as f:
    f.writelines(STOPWORD)

In [312]:
'不过' in STOPWORD

True

In [387]:
list(range(7,7))

[]

In [377]:
>>> vectorizer = TfidfVectorizer(analyzer=lambda x:[i for i in jieba.cut(x) if i not in STOPWORD])
>>> tfidf_X = vectorizer.fit_transform(sentencence)

In [378]:
tfidf_X.toarray()[2]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.13091852, 0.13091852, 0.09109838, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.25104596, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.22611726, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.25104596, 0.        , 0.        , 0.        , 0.        ,
       0.28618098, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [332]:
sen_cuted[1]

'（ 新华 / 法新 ） 新华社 北京 6 月 7 日电 （ 记者 张 旌 ） 法国 定于 6 月 11 日 举行 议会选举 首轮 投票 。'

In [342]:
from sklearn.metrics.pairwise import  cosine_similarity

In [343]:
index = 0


In [ ]:
last =False

In [379]:
for index in range(len(sentencence)-1):
    print(sentencence[index])
    simi = cosine_similarity(tfidf_X[index],tfidf_X[index+1])
    print(simi[0][0])
    if simi[0][0] <0.06:
        print('--------------------------------------------')
print(sentencence[index+1])

"2017年4月27日，在首尔光化门广场，民众在集会上手举反“萨德”标语。
0.11852061057535798
（新华社记者姚琪琳摄）新华社北京6月7日电（记者张旌）韩国国防部官员6日说，针对“萨德”在韩部署事宜，国防部方面已准备重新进行一场大规模的环境评估。
0.07453308396641231
完成新评估可能需要一年时间，“萨德”部署工作也将因此推迟或暂停。
0.12500111618653492
此前一天，青瓦台方面指责国防部试图把“萨德”对周围环境影响的评估过程“大事化小”，要求彻查此事。
0.29118161606245435
【环评“猫腻”遭曝光】韩国国防部官员6日向韩联社记者透露，青瓦台要求彻查“萨德”环境评估过程后，国防部已着手开展准备工作，将进行一场大规模的全面评估，预计可能耗时一年左右。
0.151658319177144
根据这名官员的说法，国防部将就此事与青瓦台方面沟通后再制定详细方案，具体计划尚未确定。
0.16635768013524146
这名官员同时透露，目前，针对“萨德”用地的小规模环境评估正在进行中，预计将于本月底结束。
0.24143639808408046
此前一天，青瓦台方面表示，经调查发现，国防部在“萨德”环境评估过程中存在“猫腻”，试图“大事化小”，绕过相关法律规定。
0.1860692907303759
根据韩国相关法律，要在面积超过33万平方米的土地建新设施时，必须首先通过全面环境评估，以确定对周围环境影响的程度。
0.12183871696239967
韩国为美军提供的“萨德”部署地总面积约为70万平方米，按规定本应接受大规模环境评估。
0.3018062589912216
不过，根据青瓦台方面的说法，国防部把这块地分两批提供给美军，第一批面积为32万平方米，刚好避开全面环境评估的规定，只需接受小规模非正式评估。
0.13511617444466273
余下的部分稍晚些提供，也设法躲过了大规模环境评估。
0.05101490717433696
--------------------------------------------
【部署进程或推迟】青瓦台方面发起这次调查，主要原因是要查明“另有4台发射架秘密运抵韩国”一事，而环境评估的“猫腻”正是在这一调查过程中被曝光。
0.3327022043243049

In [413]:
STOPWORDS = STOPWORD

In [463]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import  cosine_similarity
# from utils.load_data import load_stopwords
# STOPWORDS = load_stopwords()
class TfidfDecisimMaker:
    """
    将句子使用TFIDF向量化表示，判断相邻两句的cosine 相似度。相似度小于某一阈值，认为相邻的两句不相关。可以断句
    """

    def __init__(self,segmented_sentences, alpha=0.1, max_length=3):
        self.sentences = segmented_sentences
        self.alpha = alpha
        self.max_length = max_length

        self.vectorizer = TfidfVectorizer(analyzer=self.clean_words)
        #print(self.sentences)
        self.tfidf_X = self.vectorizer.fit_transform(self.sentences)
        self.doc_length = len(segmented_sentences)
        

    @staticmethod
    def clean_words(sen):
#         print(sen)
        return [s for s in sen if s not in STOPWORDS]

    def get_end_index(self,sen_index):
        base_vector = self.tfidf_X[sen_index]
        end_index = sen_index
        print(''.join(self.sentences[sen_index]))
        for i in range(sen_index+1,sen_index+self.max_length+1):
            similarity = cosine_similarity(base_vector, self.tfidf_X[i])
            if similarity[0][0] > self.alpha:
                print(similarity[0][0],''.join(self.sentences[i]))
                end_index = i
            else:
                break
        return end_index 


        

In [462]:
cuted = [jieba.lcut(sen) for sen in sentencence if sen]

tfmaker = TfidfDecisimMaker(cuted,alpha=0.2,max_length=3)

tfmaker.get_end_index(6)

这名官员同时透露，目前，针对“萨德”用地的小规模环境评估正在进行中，预计将于本月底结束。
0.24143639808408046 此前一天，青瓦台方面表示，经调查发现，国防部在“萨德”环境评估过程中存在“猫腻”，试图“大事化小”，绕过相关法律规定。


7

In [456]:
sentencence

['"2017年4月27日，在首尔光化门广场，民众在集会上手举反“萨德”标语。',
 '（新华社记者姚琪琳摄）新华社北京6月7日电（记者张旌）韩国国防部官员6日说，针对“萨德”在韩部署事宜，国防部方面已准备重新进行一场大规模的环境评估。',
 '完成新评估可能需要一年时间，“萨德”部署工作也将因此推迟或暂停。',
 '此前一天，青瓦台方面指责国防部试图把“萨德”对周围环境影响的评估过程“大事化小”，要求彻查此事。',
 '【环评“猫腻”遭曝光】韩国国防部官员6日向韩联社记者透露，青瓦台要求彻查“萨德”环境评估过程后，国防部已着手开展准备工作，将进行一场大规模的全面评估，预计可能耗时一年左右。',
 '根据这名官员的说法，国防部将就此事与青瓦台方面沟通后再制定详细方案，具体计划尚未确定。',
 '这名官员同时透露，目前，针对“萨德”用地的小规模环境评估正在进行中，预计将于本月底结束。',
 '此前一天，青瓦台方面表示，经调查发现，国防部在“萨德”环境评估过程中存在“猫腻”，试图“大事化小”，绕过相关法律规定。',
 '根据韩国相关法律，要在面积超过33万平方米的土地建新设施时，必须首先通过全面环境评估，以确定对周围环境影响的程度。',
 '韩国为美军提供的“萨德”部署地总面积约为70万平方米，按规定本应接受大规模环境评估。',
 '不过，根据青瓦台方面的说法，国防部把这块地分两批提供给美军，第一批面积为32万平方米，刚好避开全面环境评估的规定，只需接受小规模非正式评估。',
 '余下的部分稍晚些提供，也设法躲过了大规模环境评估。',
 '【部署进程或推迟】青瓦台方面发起这次调查，主要原因是要查明“另有4台发射架秘密运抵韩国”一事，而环境评估的“猫腻”正是在这一调查过程中被曝光。',
 '上月30日，青瓦台方面表示，总统文在寅获悉除目前已在韩部署的两台“萨德”系统移动发射架外，另有4台发射架已经秘密运抵韩国，感到“非常震惊”，要求彻查。',
 '青瓦台公报首席秘书尹永灿5日在记者会上说，调查已确认，瞒报事件主要责任人是国防部政策室长魏昇镐。',
 '由于魏昇镐已被停职，国防部还需重新确定一名指挥环境评估工作的负责人。',
 '青瓦台方面同时表示，将就此事展开进一步调查，以查明国防部长官韩民求和前总统朴槿惠时期的国家安保室长金宽镇是否与瞒报事件有关联。',
 '针对环评“

In [464]:
from scipy.linalg import norm

In [466]:
norm([1,1,1,1,1])

2.23606797749979

In [1]:
from scipy.linalg import norm

In [6]:
import numpy as np

In [8]:
np.array([2,3],[1,1])

5

In [9]:
np.dot([1,1],[2,2])

4